#!/bin/bash

# Create the PID file
pid_file="/var/run/myscript.pid"
echo $$ > "$pid_file"

# Display the message indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done

# Cleanup and exit
trap 'rm -f "$pid_file"; exit' SIGQUIT SIGTERM

# Handle signals
trap 'echo "I hate the kill command"; exit' SIGTERM
trap 'echo "Y U no love me?!"; exit' SIGINT
