#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code,
# and displays this data

awk '
BEGIN {
    FS=" ";
}
{
    key=$1 " " $9;
    data[key]++;
}
END {
    for (key in data) {
        print data[key], key;
    }
}' apache-access.log | sort -nr
