#!/usr/bin/env bash
# Displays best school 10x except for the 9th iteration which says Hi

CNTr = 0
while [$CNTr-lt 11]
do
if [$CNTr = 9]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    let CNTr+=1
done
